### ISSUE TITLE
Basic Ruby Tutorial

### ISSUE THREAD

**Issue by escowles** [pulibrary/ruby_for_metadataists#1]
What is the minimal amount of Ruby introduction needed to get started?

**Comment by escowles** [comment]
https://www.ruby-lang.org/en/documentation/quickstart/ looks like a good place to start.

**Comment by jrgriffiniii** [comment]
I propose to please address the following concepts:

# Variables
  - Strings
  - Numbers
  - Arrays
  - Hashes

# Control Flow Statements
  - Conditionals (`if`, `unless`, Boolean operators)
  - Iterating (`#each` and `#map`)
  - Loops

# Classes and Objects
  - Constructors
  - Instance variables
  - Methods
  - Inheritance

# Modules
  - Namespaces

I could see reducing the number of aspects addressed for `Classes and Objects`, but I fear that leaving anything else here might make it more difficult to explore the Nokogiri API.

**Comment by escowles** [comment]
@jrgriffiniii Most of that looks good to me (I agree that the basic datatypes and control flow stuff is essential).  I think we could leave out constructors, inheritance, and be very brief about namespaces since we'll mostly be focused on scripts instead of OO development.

**Comment by jrgriffiniii** [comment]
How might we attempt to address the question of IDEs or code editors?  https://ruby.github.io/TryRuby/ provides a minimal browser-based interpreter for demonstrating the basic usage of the language itself, but I suspect that some may wish to see us interact with `vim`, Atom, Visual Studio Code, or any other popular editor.

**Comment by escowles** [comment]
I'm not sure what is installed on the laptops we'll be using for the workshop.  I think that's going to be the biggest factor in what to recommend for editing.

**Comment by jrgriffiniii** [comment]
An additional item which should be covered should be regular expressions.

**Comment by jrgriffiniii** [comment]
I can see about uploading the presentation materials in Markdown for this, and will adjust these once it can be determined precisely what might be involved in working with the laptop environments for the workshop.
