### ISSUE TITLE
Nokogiri tutorial

### ISSUE THREAD

**Issue by escowles** [pulibrary/ruby_for_metadataists#3]
Quick overview of Nokogiri API usage, including:

* parsing XML files
* navigating with XPath
* doing XSL transforms
* adding/removing elements and attributes

**Comment by jrgriffiniii** [comment]
Depending upon the audience, I would also please suggest that certain potential errors with tree manipulation be mentioned (e. g. https://github.com/sparklemotion/nokogiri/issues/1912 and https://github.com/sparklemotion/nokogiri/issues/1900)

**Comment by jpstroop** [comment]
Note that with XSLT most of the staff are used to XSL >=2.0 with Saxon, where, as far as I know, libxml2/libxslt/nokogiri has never moved beyond XSL 1.0.
